/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AsrTranscribeOptions, AsrTranscriptionView } from '@deepseek-ai/dsh-asr-gateway/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$617372 {
    transcribe: (audioBase64: string, options?: AsrTranscribeOptions) => Promise<RemoteResult<AsrTranscriptionView>>
  }
  interface TypertRemoteMap {
    'asr/transcribe': (audioBase64: string, options?: AsrTranscribeOptions) => Promise<RemoteResult<AsrTranscriptionView>>
  }
  interface TypertRemoteNamespaceMap {
    'asr': TypertRemoteNamespace$617372
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
